package chat

// MediaDelta carries complete provider-generated bytes through the internal
// stream accumulator. It is not a persisted assistant-message representation
// or a progressive binary presentation event.
type MediaDelta struct {
	// Data is the complete provider-generated payload.
	Data []byte `json:"data,omitempty"`

	// MimeType is the media's MIME type as reported by the provider (e.g.
	// "image/png").
	MimeType string `json:"mime_type,omitempty"`

	// Name is an optional provider-supplied display hint, not a trusted path.
	// Materialization chooses a fallback when no usable name is available.
	Name string `json:"name,omitempty"`

	// RequestedPath is the prompt-directed target path the model asked for
	// (e.g. echoed from an "as sunshine.jpg" instruction), when one exists.
	// It is untrusted model input: the runtime routes it through
	// workspacemedia.ClassifyRequestedPath, and a path escaping the workspace
	// requires an explicit user confirmation before it is honored. The
	// runtime's response marker filter (the "[media-file: ...]" protocol,
	// pkg/runtime/generated_media_markers.go) populates it by pairing marker
	// paths with blobs in response order; blobs no marker names keep it empty
	// and materialization falls back to Name, then a generic name.
	RequestedPath string `json:"requested_path,omitempty"`

	// Size is the byte length of Data, cached because Data itself is
	// dropped once the artifact is materialized.
	Size int64 `json:"size,omitempty"`
}
